import type { Propiedad } from "./types";

export const mockPropiedades: Propiedad[] = [
  {
    id: "mock-1",
    titulo: "Apartamento en Casco Viejo",
    precio: 385000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9519,
      lng: -79.5363,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "San Felipe",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-04-01",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-2",
    titulo: "PH en Avenida Balboa",
    precio: 525000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9719,
      lng: -79.5224,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Calidonia",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-03-15",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-3",
    titulo: "Apartamento en Bella Vista",
    precio: 2400,
    moneda: "USD",
    tipoOperacion: "alquiler",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9831,
      lng: -79.5208,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Bella Vista",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-04-20",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-4",
    titulo: "Oficina en Obarrio",
    precio: 1800,
    moneda: "USD",
    tipoOperacion: "alquiler",
    categoria: "oficina",
    ubicacion: {
      lat: 8.9866,
      lng: -79.5302,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Bella Vista",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-04-05",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-5",
    titulo: "Apartamento en Marbella",
    precio: 295000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9772,
      lng: -79.5314,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Bella Vista",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-04-10",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-6",
    titulo: "Penthouse en Punta Pacífica",
    precio: 950000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9722,
      lng: -79.5063,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "San Francisco",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-03-22",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-7",
    titulo: "Apartamento en San Francisco",
    precio: 2200,
    moneda: "USD",
    tipoOperacion: "alquiler",
    categoria: "apartamento",
    ubicacion: {
      lat: 9.0028,
      lng: -79.5147,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "San Francisco",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-05-01",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-8",
    titulo: "Casa en Costa del Este",
    precio: 720000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "casa",
    ubicacion: {
      lat: 9.0017,
      lng: -79.4778,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Parque Lefevre",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-04-12",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-9",
    titulo: "Local comercial en El Cangrejo",
    precio: 4500,
    moneda: "USD",
    tipoOperacion: "alquiler",
    categoria: "local-comercial",
    ubicacion: {
      lat: 8.9854,
      lng: -79.5343,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Bella Vista",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-03-30",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-10",
    titulo: "Terreno en Clayton",
    precio: 480000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "terreno",
    ubicacion: {
      lat: 8.9956,
      lng: -79.5867,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Ancón",
    },
    fuenteId: "mock",
    urlOriginal: "#",
    imagenes: [],
    fechaPublicacion: "2026-04-25",
    fechaActualizacion: "2026-05-17",
  },
];
