import type { Propiedad } from "./types";

export const mockPropiedades: Propiedad[] = [
  {
    id: "mock-1",
    titulo: "Apartamento en Casco Viejo",
    precio: 385000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9519,
      lng: -79.5363,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "San Felipe",
    },
    areaM2: 95,
    habitaciones: 2,
    banos: 2,
    estacionamientos: 1,
    condicion: "usada",
    estadoAnuncio: "activo",
    resumenIA:
      "Apartamento usado de 95 m² en Casco Viejo, con 2 recámaras y 2 baños. Ubicación premium con valor histórico; precio por m² alto, dentro de lo esperado para la zona.",
    fuenteId: "encuentra24",
    fuenteNombre: "Encuentra24",
    urlOriginal: "https://encuentra24.com/panama/casco-viejo-apartamento-1",
    otrosAnuncios: [
      {
        fuenteId: "compreoalquile",
        fuenteNombre: "Compre o Alquile",
        urlOriginal: "https://compreoalquile.com/casco-viejo-1",
        precio: 389000,
        moneda: "USD",
        fechaDeteccion: "2026-04-04",
      },
      {
        fuenteId: "inmuebles24",
        fuenteNombre: "Inmuebles 24",
        urlOriginal: "https://inmuebles24.com/panama/casco-viejo-1",
        precio: 380000,
        moneda: "USD",
        fechaDeteccion: "2026-04-10",
      },
    ],
    fechaPublicacion: "2026-04-01",
    fechaDeteccion: "2026-04-02",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-2",
    titulo: "PH en Avenida Balboa",
    precio: 525000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9719,
      lng: -79.5224,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Calidonia",
    },
    areaM2: 180,
    habitaciones: 3,
    banos: 3,
    estacionamientos: 2,
    condicion: "nueva",
    estadoAnuncio: "activo",
    resumenIA:
      "Penthouse nuevo de 180 m² sobre Av. Balboa con vista al mar. 3 recámaras, 3 baños y 2 estacionamientos. Precio por m² está en el rango alto de la zona, justificado por la ubicación y la condición.",
    fuenteId: "compreoalquile",
    fuenteNombre: "Compre o Alquile",
    urlOriginal: "https://compreoalquile.com/balboa-ph-2",
    fechaPublicacion: "2026-03-15",
    fechaDeteccion: "2026-03-16",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-3",
    titulo: "Apartamento en Bella Vista",
    precio: 2400,
    moneda: "USD",
    tipoOperacion: "alquiler",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9831,
      lng: -79.5208,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Bella Vista",
    },
    areaM2: 110,
    habitaciones: 2,
    banos: 2,
    estacionamientos: 1,
    condicion: "usada",
    estadoAnuncio: "activo",
    resumenIA:
      "Apartamento usado de 110 m² en Bella Vista para alquilar. 2 recámaras y 2 baños, con 1 estacionamiento. Renta competitiva para el corregimiento.",
    fuenteId: "encuentra24",
    fuenteNombre: "Encuentra24",
    urlOriginal: "https://encuentra24.com/panama/bella-vista-3",
    fechaPublicacion: "2026-04-20",
    fechaDeteccion: "2026-04-21",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-4",
    titulo: "Oficina en Obarrio",
    precio: 1800,
    moneda: "USD",
    tipoOperacion: "alquiler",
    categoria: "oficina",
    ubicacion: {
      lat: 8.9866,
      lng: -79.5302,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Bella Vista",
    },
    areaM2: 85,
    estacionamientos: 2,
    condicion: "usada",
    estadoAnuncio: "activo",
    resumenIA:
      "Oficina usada de 85 m² en Obarrio, con 2 estacionamientos. Zona corporativa consolidada; renta dentro del promedio del corregimiento.",
    fuenteId: "compreoalquile",
    fuenteNombre: "Compre o Alquile",
    urlOriginal: "https://compreoalquile.com/obarrio-oficina-4",
    fechaPublicacion: "2026-04-05",
    fechaDeteccion: "2026-04-06",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-5",
    titulo: "Apartamento en Marbella",
    precio: 295000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9772,
      lng: -79.5314,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Bella Vista",
    },
    areaM2: 105,
    habitaciones: 2,
    banos: 2,
    estacionamientos: 1,
    condicion: "usada",
    estadoAnuncio: "activo",
    resumenIA:
      "Apartamento usado de 105 m² en Marbella, 2 recámaras y 2 baños. Precio por m² ligeramente por debajo de la media de la zona — posible oportunidad.",
    fuenteId: "encuentra24",
    fuenteNombre: "Encuentra24",
    urlOriginal: "https://encuentra24.com/panama/marbella-5",
    fechaPublicacion: "2026-04-10",
    fechaDeteccion: "2026-04-11",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-6",
    titulo: "Penthouse en Punta Pacífica",
    precio: 950000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "apartamento",
    ubicacion: {
      lat: 8.9722,
      lng: -79.5063,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "San Francisco",
    },
    areaM2: 280,
    habitaciones: 4,
    banos: 4,
    estacionamientos: 3,
    condicion: "nueva",
    estadoAnuncio: "activo",
    resumenIA:
      "Penthouse nuevo de 280 m² en Punta Pacífica frente al mar. 4 recámaras, 4 baños, 3 estacionamientos. Producto premium; precio por m² alto pero consistente con propiedades comparables.",
    fuenteId: "inmuebles24",
    fuenteNombre: "Inmuebles 24",
    urlOriginal: "https://inmuebles24.com/panama/punta-pacifica-6",
    fechaPublicacion: "2026-03-22",
    fechaDeteccion: "2026-03-23",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-7",
    titulo: "Apartamento en San Francisco",
    precio: 2200,
    moneda: "USD",
    tipoOperacion: "alquiler",
    categoria: "apartamento",
    ubicacion: {
      lat: 9.0028,
      lng: -79.5147,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "San Francisco",
    },
    areaM2: 120,
    habitaciones: 3,
    banos: 2,
    estacionamientos: 2,
    condicion: "usada",
    estadoAnuncio: "activo",
    resumenIA:
      "Apartamento usado de 120 m² en San Francisco, con 3 recámaras, 2 baños y 2 estacionamientos. Su precio por m² está dentro del rango medio de la zona.",
    fuenteId: "encuentra24",
    fuenteNombre: "Encuentra24",
    urlOriginal: "https://encuentra24.com/panama/san-francisco-7",
    otrosAnuncios: [
      {
        fuenteId: "compreoalquile",
        fuenteNombre: "Compre o Alquile",
        urlOriginal: "https://compreoalquile.com/san-francisco-7",
        precio: 2250,
        moneda: "USD",
        fechaDeteccion: "2026-05-14",
      },
    ],
    fechaPublicacion: "2026-05-01",
    fechaDeteccion: "2026-05-12",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-8",
    titulo: "Casa en Costa del Este",
    precio: 720000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "casa",
    ubicacion: {
      lat: 9.0017,
      lng: -79.4778,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Parque Lefevre",
    },
    areaM2: 340,
    habitaciones: 4,
    banos: 4,
    estacionamientos: 3,
    condicion: "usada",
    estadoAnuncio: "activo",
    resumenIA:
      "Casa usada de 340 m² en Costa del Este, 4 recámaras y 4 baños. Zona residencial consolidada; precio por m² competitivo respecto a comparables recientes.",
    fuenteId: "compreoalquile",
    fuenteNombre: "Compre o Alquile",
    urlOriginal: "https://compreoalquile.com/costa-del-este-8",
    otrosAnuncios: [
      {
        fuenteId: "encuentra24",
        fuenteNombre: "Encuentra24",
        urlOriginal: "https://encuentra24.com/panama/costa-del-este-8",
        precio: 715000,
        moneda: "USD",
        fechaDeteccion: "2026-04-15",
      },
      {
        fuenteId: "inmuebles24",
        fuenteNombre: "Inmuebles 24",
        urlOriginal: "https://inmuebles24.com/panama/costa-del-este-8",
        precio: 729000,
        moneda: "USD",
        fechaDeteccion: "2026-04-20",
      },
    ],
    fechaPublicacion: "2026-04-12",
    fechaDeteccion: "2026-04-13",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-9",
    titulo: "Local comercial en El Cangrejo",
    precio: 4500,
    moneda: "USD",
    tipoOperacion: "alquiler",
    categoria: "local-comercial",
    ubicacion: {
      lat: 8.9854,
      lng: -79.5343,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Bella Vista",
    },
    areaM2: 160,
    estacionamientos: 2,
    condicion: "usada",
    estadoAnuncio: "activo",
    resumenIA:
      "Local comercial usado de 160 m² en El Cangrejo, ideal para restaurante/oficina. Tráfico peatonal alto. Renta dentro del promedio comercial de la zona.",
    fuenteId: "inmuebles24",
    fuenteNombre: "Inmuebles 24",
    urlOriginal: "https://inmuebles24.com/panama/el-cangrejo-9",
    fechaPublicacion: "2026-03-30",
    fechaDeteccion: "2026-03-31",
    fechaActualizacion: "2026-05-17",
  },
  {
    id: "mock-10",
    titulo: "Terreno en Clayton",
    precio: 480000,
    moneda: "USD",
    tipoOperacion: "venta",
    categoria: "terreno",
    ubicacion: {
      lat: 8.9956,
      lng: -79.5867,
      provincia: "Panamá",
      distrito: "Panamá",
      corregimiento: "Ancón",
    },
    areaM2: 820,
    condicion: "usada",
    estadoAnuncio: "activo",
    resumenIA:
      "Terreno de 820 m² en Clayton, con uso residencial. Zona en crecimiento; precio por m² bajo respecto a la media de venta de terrenos en el corregimiento.",
    fuenteId: "encuentra24",
    fuenteNombre: "Encuentra24",
    urlOriginal: "https://encuentra24.com/panama/clayton-10",
    fechaPublicacion: "2026-04-25",
    fechaDeteccion: "2026-04-26",
    fechaActualizacion: "2026-05-17",
  },
];
